### 2.2 파이썬 리스트를 데이터프레임으로 생성

In [8]:
import pandas as pd

df = pd.DataFrame([ ['Kim',27,92], 
                    ['Lee', 33,98],
                    ['Park',19, 87] ])
df

      0   1   2
0   Kim  27  92
1   Lee  33  98
2  Park  19  87

### 2.3 파이썬 딕셔너리를 데이터프레임으로 생성

In [9]:
import pandas as pd

df = pd.DataFrame({'name':['Kim','Lee','Park'],
                    'age':[27, 33,19],
                  'score':[92,98,87]})
df

   name  age  score
0   Kim   27     92
1   Lee   33     98
2  Park   19     87

### 2.4 파일을 읽어서 데이터프레임으로 생성 : CSV파일

In [57]:
import pandas as pd
df= pd.read_csv('data.csv', encoding='UTF-8'  )
df

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

### 2.5 파일을 읽어서 데이터프레임으로 생성 : xlsx파일

In [1]:
import pandas as pd

df = pd.read_excel('data.xlsx')
df

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

### 2.6 데이터프레임 데이터 보기

In [3]:
df.head(3)

    반   이름 성별    국어    수학 응시여부 확인여부
0  A반  구이서  남  90.0  89.0   응시   확인
1  B반  김이정  여  78.0  45.0   응시   확인
2  A반  오지수  남   NaN   NaN   응시   확인

In [2]:
import pandas as pd

df = pd.read_excel('data.xlsx')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   반       10 non-null     object
 1   이름      10 non-null     object
 2   성별      10 non-null     object
 3   국어      7 non-null      float64
 4   수학      7 non-null      float64
 5   응시여부    8 non-null      object
 6   확인여부    7 non-null      object
dtypes: float64(2), object(5)
memory usage: 688.0+ bytes

In [4]:
df['이름'] # df.이름

0    구이서
1    김이정
2    오지수
3    김선후
4    하진희
5    강현진
6    김진솔
7    박서준
8    김성희
9    이지서
Name: 이름, dtype: object

In [5]:
df[['이름','성별']]

    이름 성별
0  구이서  남
1  김이정  여
2  오지수  남
3  김선후  남
4  하진희  여
5  강현진  남
6  김진솔  남
7  박서준  여
8  김성희  남
9  이지서  여

In [4]:
df[0:3]

    반   이름 성별    국어    수학 응시여부 확인여부
0  A반  구이서  남  90.0  89.0   응시   확인
1  B반  김이정  여  78.0  45.0   응시   확인
2  A반  오지수  남   NaN   NaN   응시   확인

In [14]:
df['이름'][0:3]

0    구이서
1    김이정
2    오지수
Name: 이름, dtype: object

In [15]:
df.loc[2]

반        A반
이름      오지수
성별        남
국어      NaN
수학      NaN
응시여부     응시
확인여부     확인
Name: 2, dtype: object

In [17]:
df.loc[0:3,['이름']]

    이름
0  구이서
1  김이정
2  오지수
3  김선후

In [9]:
df.iloc[1,2]

'여'

In [18]:
df.iloc[0:3,0:2]

    반   이름
0  A반  구이서
1  B반  김이정
2  A반  오지수

In [59]:
df['국어']>=80

0     True
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9     True
Name: 국어, dtype: bool

In [60]:
df[df['국어']>=80]

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
6  B반  김진솔  남  90.0   89.0   응시   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [61]:
df.query('국어>=80')

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
6  B반  김진솔  남  90.0   89.0   응시   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [3]:
df1 = df[df['국어']>=80]
df1

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
6  B반  김진솔  남  90.0   89.0   응시   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [62]:
df.query('국어>=80 and 수학>=90')

    반   이름 성별    국어     수학 응시여부 확인여부
9  B반  이지서  여  86.0  100.0   응시   확인

In [65]:
df.query('국어>=80 or 수학>=90')

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
6  B반  김진솔  남  90.0   89.0   응시   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [4]:
df[(df['국어'] >= 80) | (df['수학'] >= 90)]

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
6  B반  김진솔  남  90.0   89.0   응시   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [66]:
df.sort_values(by=['이름'])

    반   이름 성별    국어     수학 응시여부 확인여부
5  A반  강현진  남   NaN    NaN  NaN  NaN
0  A반  구이서  남  90.0   89.0   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
8  A반  김성희  남   NaN    NaN  NaN   확인
1  B반  김이정  여  78.0   45.0   응시   확인
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
9  B반  이지서  여  86.0  100.0   응시   확인
4  A반  하진희  여   0.0   85.0   응시  NaN

In [6]:
print(list(df.index))
print(list(df.columns))
print(df.size)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
['반', '이름', '성별', '국어', '수학', '응시여부', '확인여부']
70

In [9]:
type(df.columns)

pandas.core.indexes.base.Index

### 3.1 데이터프레임 데이터 집계

In [67]:
df.describe()

             국어          수학
count   7.00000    7.000000
mean   65.00000   71.000000
std    34.82815   25.053277
min     0.00000   44.000000
25%    55.50000   45.000000
50%    78.00000   85.000000
75%    88.00000   89.000000
max    90.00000  100.000000

In [5]:
df.value_counts()

반   이름   성별  국어    수학     응시여부  확인여부
A반  구이서  남   90.0  89.0   응시    확인      1
B반  김이정  여   78.0  45.0   응시    확인      1
    김진솔  남   90.0  89.0   응시    확인      1
    박서준  여   78.0  45.0   응시    확인      1
    이지서  여   86.0  100.0  응시    확인      1
dtype: int64

In [21]:
df['반'].value_counts()

A반    5
B반    5
Name: 반, dtype: int64

In [68]:
df['국어'].sum()

455.0

In [25]:
df['국어'].mean()

65.0

In [26]:
df.groupby('반').sum()

       국어     수학
반
A반   90.0  174.0
B반  365.0  323.0

In [27]:
df.groupby('반').mean()

      국어    수학
반
A반  45.0  87.0
B반  73.0  64.6

### 3.2 데이터프레임의 결측치 처리

In [7]:
df.isna()

       반     이름     성별     국어     수학   응시여부   확인여부
0  False  False  False  False  False  False  False
1  False  False  False  False  False  False  False
2  False  False  False   True   True  False  False
3  False  False  False  False  False  False   True
4  False  False  False  False  False  False   True
5  False  False  False   True   True   True   True
6  False  False  False  False  False  False  False
7  False  False  False  False  False  False  False
8  False  False  False   True   True   True  False
9  False  False  False  False  False  False  False

In [8]:
df.isna().sum()

반       0
이름      0
성별      0
국어      3
수학      3
응시여부    2
확인여부    3
dtype: int64

In [28]:
df.fillna({'확인여부':'완료'})

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시   완료
4  A반  하진희  여   0.0   85.0   응시   완료
5  A반  강현진  남   NaN    NaN  NaN   완료
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [29]:
df.fillna(0)

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   0.0    0.0   응시   확인
3  B반  김선후  남  33.0   44.0   응시    0
4  A반  하진희  여   0.0   85.0   응시    0
5  A반  강현진  남   0.0    0.0    0    0
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   0.0    0.0    0   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [72]:
df

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [4]:
df2=df.dropna(subset=['국어'])
df2

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [5]:
df3= df.dropna()
df3

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [79]:
df.groupby('반').mean()

      국어    수학
반
A반  45.0  87.0
B반  73.0  64.6

In [80]:
df2.groupby('반').mean()

      국어    수학
반
A반  45.0  87.0
B반  73.0  64.6

In [33]:
df3.groupby('반').mean()

      국어     수학
반
A반  90.0  89.00
B반  83.0  69.75

In [45]:
df.isna().sum()

반       0
이름      0
성별      0
국어      3
수학      3
응시여부    2
확인여부    3
dtype: int64

In [6]:
df2.isna().sum()

반       0
이름      0
성별      0
국어      0
수학      0
응시여부    0
확인여부    2
dtype: int64

In [46]:
df3.isna().sum()

반       0
이름      0
성별      0
국어      0
수학      0
응시여부    0
확인여부    0
dtype: int64

### 3.3 데이터프레임의 변경

In [7]:
df['총점'] = df['국어'] + df['수학']
df

    반   이름 성별    국어     수학 응시여부 확인여부     총점
0  A반  구이서  남  90.0   89.0   응시   확인  179.0
1  B반  김이정  여  78.0   45.0   응시   확인  123.0
2  A반  오지수  남   NaN    NaN   응시   확인    NaN
3  B반  김선후  남  33.0   44.0   응시  NaN   77.0
4  A반  하진희  여   0.0   85.0   응시  NaN   85.0
5  A반  강현진  남   NaN    NaN  NaN  NaN    NaN
6  B반  김진솔  남  90.0   89.0   응시   확인  179.0
7  B반  박서준  여  78.0   45.0   응시   확인  123.0
8  A반  김성희  남   NaN    NaN  NaN   확인    NaN
9  B반  이지서  여  86.0  100.0   응시   확인  186.0

In [3]:
import pandas as pd

df = pd.read_excel('data.xlsx')
df

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
2  A반  오지수  남   NaN    NaN   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
5  A반  강현진  남   NaN    NaN  NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
8  A반  김성희  남   NaN    NaN  NaN   확인
9  B반  이지서  여  86.0  100.0   응시   확인

In [5]:
df.drop('확인여부',axis=1)

    반   이름 성별    국어     수학 응시여부
0  A반  구이서  남  90.0   89.0   응시
1  B반  김이정  여  78.0   45.0   응시
2  A반  오지수  남   NaN    NaN   응시
3  B반  김선후  남  33.0   44.0   응시
4  A반  하진희  여   0.0   85.0   응시
5  A반  강현진  남   NaN    NaN  NaN
6  B반  김진솔  남  90.0   89.0   응시
7  B반  박서준  여  78.0   45.0   응시
8  A반  김성희  남   NaN    NaN  NaN
9  B반  이지서  여  86.0  100.0   응시

In [8]:
import pandas as pd

df1 = pd.DataFrame( {'기호':['a','B','c','d','e'],
                   '단가':[100, 0, 0, 400, 500],
                    '수량':[1, 1, 1, 2 , 0] } )
df1

  기호   단가  수량
0  a  100   1
1  B    0   1
2  c    0   1
3  d  400   2
4  e  500   0

In [9]:
df1.replace(0, 7)

  기호   단가  수량
0  a  100   1
1  B    7   1
2  c    7   1
3  d  400   2
4  e  500   7

In [10]:
df1.replace({1:10, 2:20})

  기호   단가  수량
0  a  100  10
1  B    0  10
2  c    0  10
3  d  400  20
4  e  500   0

In [11]:
df1.replace({'단가':{0:1000}, '수량':{0:100}})

  기호    단가   수량
0  a   100    1
1  B  1000    1
2  c  1000    1
3  d   400    2
4  e   500  100